language: node_js
node_js:
  - 4.2
addons:
  code_climate:
    repo_token: dcb24cd044d9f5f99120c795960bd3b5e54491640d76b3513d67d6499a01f3bf
before_install:
  - npm install -g grunt-cli
  - npm install -g codeclimate-test-reporter
before_script: bower install
script:
  - grunt test
  - grunt coverage:node
  - grunt coveralls
after_script:
  - codeclimate-test-reporter < .tmp/lcov.info
  - ./node_modules/.bin/codacy-coverage < .tmp/lcov.info
sudo: false